### ISSUE TITLE
Error when install package in Mouf

### ISSUE THREAD

**Issue by gulien** [thecodingmachine/security.forgot-your-password#1]
When I try to install this package with Mouf, I got this error:
Fatal error: Uncaught Mouf\MoufException: Instance 'forgotYourPasswordMailTemplate' does not exist. in /var/www/html/vendor/mouf/mouf/src/Mouf/MoufManager.php on line 1942

**Comment by xhuberty** [comment]
I think that @moufmouf forget to export the forgotYourPasswordMailTemplate instance of 'thecodingmachine/swift-twig-mail-template'

**Comment by moufmouf** [comment]
Should be fixed now.
